### ISSUE TITLE
Palette swap option crashes preview when selecting 'variant' on beasties without a variant palette

### ISSUE THREAD

**Issue by indoorfox** [JdavisBro/beastieball#15]
Pretty much all in the title-
Selecting a beastie in the beastiepedia which does not have a variant palette, then palette swapping them with a beastie which _does_ have a variant palette, causes a 'variant' tab to appear on the preview. Selecting that tab crashes the preview. This error does not occur when palette swapping between two beasties who both have variant palettes.

Exact error readout:
```
TypeError: Cannot read properties of undefined (reading 'array')
    at https://beastieball.info/assets/Beastiepedia-BZ9pioWP.js:2:10141
    at Array.forEach (<anonymous>)
    at https://beastieball.info/assets/Beastiepedia-BZ9pioWP.js:2:10076
    at ii (https://beastieball.info/assets/index-jJ5yIuaA.js:41:24263)
    at fr (https://beastieball.info/assets/index-jJ5yIuaA.js:41:42275)
    at kv (https://beastieball.info/assets/index-jJ5yIuaA.js:41:41128)
    at _n (https://beastieball.info/assets/index-jJ5yIuaA.js:41:40185)
    at vc (https://beastieball.info/assets/index-jJ5yIuaA.js:41:36812)
    at gn (https://beastieball.info/assets/index-jJ5yIuaA.js:39:3272)
    at https://beastieball.info/assets/index-jJ5yIuaA.js:41:34199```

**Comment by JdavisBro** [comment]
think i fixed this with f6dec60
